---
exclude_paths:
  - "docs/**"
  - "tally_ho/libs/**"
  - "**.min.js"
  - "**.min.css"
  - "tally_ho/apps/tally/static/js/get_centers_stations.js"
  - "tally_ho/apps/tally/static/css/default.css"
  - "tally_ho/apps/tally/static/js/data_table.js"
