---
exclude_paths:
  - "docs/**"
  - "tally_ho/libs/**"
  - "**.min.js"
  - "**.min.css"
  - "tally_ho/apps/tally/static/js/get_centers_stations.js"
  - "tally_ho/apps/tally/static/css/default.css"
  - "tally_ho/apps/tally/static/js/data_table.js"
  - "tally_ho/apps/tally/static/js/download_regions.js"
  - "tally_ho/apps/tally/static/js/download_offices.js"
  - "tally_ho/apps/tally/static/js/download_results.js"
  - "tally_ho/apps/tally/static/js/download_result_forms.js"
  - "tally_ho/apps/tally/static/js/download_centers_and_stations_list.js"
  - "tally_ho/apps/tally/static/js/download_candidates_list.js"
