services:
  db1:
    image: postgres:15-alpine
    env_file:
      - config/db/db1_env
    networks:
      - db1_net
    volumes:
      - db1_volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - db1_net
  memcached:
    image: memcached:1.6-alpine
    ports:
      - 11211:11211
    networks:
      - db1_net
  web:
    build: .
    environment:
      TALLY_HO_HTTP_PORT: ${TALLY_HO_HTTP_PORT:-8000}
      DJANGO_SETTINGS_MODULE: tally_ho.settings.docker
    command: >
      bash -c "python manage.py migrate --settings=tally_ho.settings.docker
      && python manage.py collectstatic --noinput --settings=tally_ho.settings.docker
      && python manage.py create_groups --settings=tally_ho.settings.docker
      && python manage.py create_demo_users --settings=tally_ho.settings.docker
      && python manage.py create_demo_tally --settings=tally_ho.settings.docker
      && DJANGO_SETTINGS_MODULE=tally_ho.settings.docker gunicorn --reload --limit-request-line 6000 --chdir /code --bind :8000 tally_ho.wsgi:application"
    volumes:
      - .:/code
      - static_volume:/code/tally_ho/static
      - media_volume:/code/tally_ho/media
    depends_on:
      - db1
      - redis
      - memcached
    networks:
      - nginx_net
      - db1_net
  worker:
    build: .
    command: >
      celery -A tally_ho.celeryapp worker
      --loglevel=info -Q tally_data_import,celery
    environment:
      DJANGO_SETTINGS_MODULE: tally_ho.settings.docker
    volumes:
      - .:/code
      - media_volume:/code/tally_ho/media
    depends_on:
      - db1
      - redis
      - memcached
    networks:
      - db1_net
  nginx:
    command: >
      sh -c "sleep 2 && nginx -g 'daemon off;'"
    image: nginx:stable-alpine
    ports:
      - ${TALLY_HO_HTTP_PORT:-8000}:80
      # change to 80:80 for production
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/code/tally_ho/static
      - media_volume:/code/tally_ho/media
    depends_on:
      - web
    networks:
      - nginx_net

networks:
  nginx_net:
    driver: bridge
  db1_net:
    driver: bridge

volumes:
  db1_volume:
  static_volume:
  media_volume:
