from django_enumfield import enum


class FormState(enum.Enum):
    ARCHIVED = 0
    ARCHIVING = 1
    AUDIT = 2
    CLEARANCE = 3
    CORRECTION = 4
    DATA_ENTRY_1 = 5
    DATA_ENTRY_2 = 6
    INTAKE = 7
    QUALITY_CONTROL = 8
    UNSUBMITTED = 9
    AUDIT_PENDING_STATE = 10
    CLEARANCE_PENDING_STATE = 11

    _transitions = {
        ARCHIVED: (ARCHIVING, AUDIT),
        ARCHIVING: (QUALITY_CONTROL,),
        AUDIT: (ARCHIVING, CORRECTION, DATA_ENTRY_1, DATA_ENTRY_2,
                ARCHIVED, QUALITY_CONTROL),
        CLEARANCE: (ARCHIVING, INTAKE, UNSUBMITTED, CORRECTION, AUDIT,
                    ARCHIVED, DATA_ENTRY_1, DATA_ENTRY_2, QUALITY_CONTROL, CLEARANCE_PENDING_STATE),
        CORRECTION: (DATA_ENTRY_2,),
        DATA_ENTRY_1: (AUDIT, CORRECTION, INTAKE, QUALITY_CONTROL, ARCHIVING),
        DATA_ENTRY_2: (DATA_ENTRY_1, AUDIT_PENDING_STATE, CLEARANCE_PENDING_STATE),
        INTAKE: (CLEARANCE, UNSUBMITTED),
        QUALITY_CONTROL: (CORRECTION,),
        UNSUBMITTED: (CLEARANCE, INTAKE, CLEARANCE_PENDING_STATE),
        CLEARANCE_PENDING_STATE: (CLEARANCE,),
        AUDIT_PENDING_STATE: (AUDIT,)
    }
