from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import JsonResponse
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from tally_ho.apps.tally.forms.login_form import LoginForm
from tally_ho.apps.tally.forms.password_change import PasswordChangeForm
from tally_ho.apps.tally.views import (audit, clearance, corrections,
                                       data_entry, home, intake, profile,
                                       quality_control, super_admin,
                                       tally_manager)
from tally_ho.apps.tally.views.data import (ballot_list_view,
                                            candidate_list_view,
                                            center_list_view,
                                            electrol_race_list_view,
                                            form_list_view, office_list_view,
                                            region_list_view,
                                            sub_constituency_list_view,
                                            tally_list_view, user_list_view)
from tally_ho.apps.tally.views.reports import (administrative_areas_reports,
                                               candidate_list_by_votes,
                                               candidate_results,
                                               election_statistics_report,
                                               offices, overall_votes,
                                               progress_by_sub_races_reports,
                                               races,
                                               staff_performance_metrics,
                                               station_progress_report)
from tally_ho.apps.tally.views.reports import \
    valid_and_invalid_votes_by_admin_area as admin_area_reports
from tally_ho.apps.tally.views.reports import votes_per_candidate
from tally_ho.apps.tally.views.reports.administrative_areas_reports import (
    ClearanceAuditSummaryReportDataView, ClearanceAuditSummaryReportView)
from tally_ho.apps.tally.views.reports.overvoted_forms import (
    OvervotedResultFormsDataView, OvervotedResultFormsView)
from tally_ho.apps.tally.views.reports.turnout_reports_by_admin_areas import (
    TurnoutReportByAdminAreasDataView, TurnoutReportByAdminAreasView)
from tally_ho.apps.tally.views.reports.turnout_reports_by_gender import (
    TurnoutReportByGenderAndAdminAreasDataView,
    TurnoutReportByGenderAndAdminAreasView)
from tally_ho.apps.tally.views.workflow import (CreateRecallRequestView,
                                                InitiateRecallView,
                                                RecallRequestDetailView,
                                                ViewResultFormDetailsView)

admin.autodiscover()

accounts_urls = [
    path(
        "login/",
        profile.login,
        {
            "template_name": "registration/login.html",
            "authentication_form": LoginForm,
        },
        name="login",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(form_class=PasswordChangeForm),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        {"next_page": settings.LOGOUT_REDIRECT_URL},
        name="logout",
    ),
]

handler403 = "tally_ho.apps.tally.views.home.permission_denied"
handler404 = "tally_ho.apps.tally.views.home.not_found"
handler400 = "tally_ho.apps.tally.views.home.bad_request"
handler500 = "tally_ho.apps.tally.views.home.server_error"

urlpatterns = [
    path("", home.HomeView.as_view(), name="home"),
    path("locale", home.LocaleView.as_view(), name="home-locale"),
    path("not-tally", home.NoTallyView.as_view(), name="home-no-tally"),
    re_path(
        r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}
    ),
    re_path(
        r"^data/center-list/(?P<tally_id>(\d+))/$",
        center_list_view.CenterListView.as_view(),
        name="center-list",
    ),
    re_path(
        r"^ajax/download-centers-and-stations-list/$",
        center_list_view.get_centers_stations_list,
        name="download-centers-and-stations-list",
    ),
    re_path(
        r"^data/turnout-list/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        TurnoutReportByAdminAreasView.as_view(),
        name="turnout-list",
    ),
    re_path(
        r"^data/turnout-list-data/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        TurnoutReportByAdminAreasDataView.as_view(),
        name="turnout-list-data",
    ),
    re_path(
        r"^data/turnout-report-by-gender/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        TurnoutReportByGenderAndAdminAreasView.as_view(),
        name="turnout-report-by-gender",
    ),
    re_path(
        r"^data/turnout-report-by-gender-data/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        TurnoutReportByGenderAndAdminAreasDataView.as_view(),
        name="turnout-report-by-gender-data",
    ),
    re_path(
        r"^data/valid-and-invalid-votes-by-admin-area/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        admin_area_reports.ValidAndInvalidVotesByAdminAreasView.as_view(),
        name="valid-and-invalid-votes-by-admin-area",
    ),
    re_path(
        r"^data/valid-and-invalid-votes-by-adminarea-data/(?P<tally_id>(\d+))/"
        r"(?:(?P<admin_level>\w+)/)?$",
        admin_area_reports.ValidAndInvalidVotesByAdminAreasDataView.as_view(),
        name="valid-and-invalid-votes-by-adminarea-data",
    ),
    re_path(
        r"^data/summary-list/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.SummaryReportView.as_view(),
        name="summary-list",
    ),
    re_path(
        r"^data/summary-list/(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.SummaryReportView.as_view(),
        name="constituency-summary-report",
    ),
    re_path(
        r"^data/summary-list/(?P<tally_id>(\d+))"
        r"/(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SummaryReportView.as_view(),
        name="sub-constituency-summary-report",
    ),
    re_path(
        r"^data/stations-and-centers-under-investigation-list/"
        r"(?P<tally_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="stations-and-centers-under-investigation-list",
    ),
    re_path(
        r"^data/cons-stations-and-centers-under-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="cons-stations-and-centers-under-investigation",
    ),
    re_path(
        r"^data/sub-cons-stations-and-centers-under-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="sub-cons-stations-and-centers-under-investigation",
    ),
    re_path(
        r"^data/stations-and-centers-under-process-audit-list/"
        r"(?P<tally_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="stations-and-centers-under-process-audit-list",
    ),
    re_path(
        r"^data/cons-stations-and-centers-under-process-audit-list/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="cons-stations-and-centers-under-process-audit-list",
    ),
    re_path(
        r"^data/sub-cons-stations-and-centers-under-process-audit-list/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="sub-cons-stations-and-centers-under-process-audit-list",
    ),
    re_path(
        r"^data/progressive-report-list/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportView.as_view(),
        name="progressive-report-list",
    ),
    re_path(
        r"^data/cons-progressive-report-list/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportView.as_view(),
        name="cons-progressive-report-list",
    ),
    re_path(
        r"^data/sub-cons-progressive-report-list/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportView.as_view(),
        name="sub-cons-progressive-report-list",
    ),
    re_path(
        r"^data/stations-and-centers-excluded-after-investigation-list/"
        r"(?P<tally_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="stations-and-centers-excluded-after-investigation-list",
    ),
    re_path(
        r"^data/cons-stations-and-centers-excluded-after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="cons-stations-and-centers-excluded-after-investigation",
    ),
    re_path(
        r"^data/"
        r"sub-cons-stations-and-centers-excluded-after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportView.as_view(),
        name="sub-cons-stations-and-centers-excluded-after-investigation",
    ),
    re_path(
        r"^data/summary-list-data/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.SummaryReportDataView.as_view(),
        name="summary-list-data",
    ),
    re_path(
        r"^data/summary-list-data/(?P<tally_id>(\d+))"
        r"/(?P<region_id>(\d+))/$",
        administrative_areas_reports.SummaryReportDataView.as_view(),
        name="summary-list-data",
    ),
    re_path(
        r"^data/summary-list-data/(?P<tally_id>(\d+))"
        r"/(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SummaryReportDataView.as_view(),
        name="summary-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-investigation-list-data/"
        r"(?P<tally_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-investigation-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-investigation-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-investigation-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-investigation-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-investigation-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-process-audit-list-data/"
        r"(?P<tally_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-process-audit-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-process-audit-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-process-audit-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-under-process-audit-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-under-process-audit-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-under-process-audit-list-data",
    ),
    re_path(
        r"^data/stations-and-centers-excluded-after-investigation-data/"
        r"(?P<tally_id>(\d+))/"
        r"(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-excluded-after-investigation-data",
    ),
    re_path(
        r"^data/stations-and-centers-excluded-after-investigation-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-excluded-after-investigation-data",
    ),
    re_path(
        r"^data/stations-and-centers-excluded-after-investigation-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<report_name>"
        r"(stations-and-centers-excluded-after-investigation-list))/$",
        administrative_areas_reports.DiscrepancyReportDataView.as_view(),
        name="stations-and-centers-excluded-after-investigation-data",
    ),
    re_path(
        r"^data/progressive-report-list-data/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportDataView.as_view(),
        name="progressive-report-list-data",
    ),
    re_path(
        r"^data/progressive-report-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportDataView.as_view(),
        name="progressive-report-list-data",
    ),
    re_path(
        r"^data/progressive-report-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.ProgressiveReportDataView.as_view(),
        name="progressive-report-list-data",
    ),
    re_path(
        r"^data/center-list/(?P<tally_id>(\d+))/(?P<format>(csv))/$",
        center_list_view.CenterListView.as_view(),
        name="center-list-csv",
    ),
    re_path(
        r"^data/center-list-data/(?P<tally_id>(\d+))/$",
        center_list_view.CenterListDataView.as_view(),
        name="center-list-data",
    ),
    re_path(
        r"^data/center-list/(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        center_list_view.CenterListView.as_view(),
        name="center-and-stations-list",
    ),
    re_path(
        r"^data/center-list-data/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/$",
        center_list_view.CenterListDataView.as_view(),
        name="center-list-data",
    ),
    re_path(
        r"^data/center-list/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/$",
        center_list_view.CenterListView.as_view(),
        name="center-and-stations-list",
    ),
    re_path(
        r"^data/center-list-data/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/$",
        center_list_view.CenterListDataView.as_view(),
        name="center-list-data",
    ),
    re_path(
        r"^data/center-list/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/$",
        center_list_view.CenterListView.as_view(),
        name="center-and-stations-list",
    ),
    re_path(
        r"^data/center-list-data/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/$",
        center_list_view.CenterListDataView.as_view(),
        name="center-list-data",
    ),
    re_path(
        r"^data/ballot-list-data/(?P<tally_id>(\d+))/$",
        ballot_list_view.BallotListDataView.as_view(),
        name="ballot-list-data",
    ),
    re_path(
        r"^data/ballot-list/(?P<tally_id>(\d+))/$",
        ballot_list_view.BallotListView.as_view(),
        name="ballot-list",
    ),
    re_path(
        r"^data/candidate-list/(?P<tally_id>(\d+))/$",
        candidate_list_view.CandidateListView.as_view(),
        name="candidate-list",
    ),
    re_path(
        r"^data/candidate-list-data/(?P<tally_id>(\d+))/$",
        candidate_list_view.CandidateListDataView.as_view(),
        name="candidate-list-data",
    ),
    re_path(
        r"^reports/internal/candidate-list-by-votes/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListView.as_view(),
        name="candidate-list-by-votes",
    ),
    re_path(
        r"^reports/internal/candidates-list-by-votes-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListDataView.as_view(),
        name="candidates-list-by-votes-list-data",
    ),
    re_path(
        r"^reports/internal/candidate-list-by-votes/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListView.as_view(),
        name="candidate-list-by-votes",
    ),
    re_path(
        r"^reports/internal/candidates-list-by-votes-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListDataView.as_view(),
        name="candidates-list-by-votes-list-data",
    ),
    re_path(
        r"^reports/internal/candidate-list-by-votes/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListView.as_view(),
        name="candidate-list-by-votes",
    ),
    re_path(
        r"^reports/internal/candidates-list-by-votes-list-data/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/(?P<sub_constituency_id>(\d+))/$",
        candidate_list_by_votes.CandidateVotesListDataView.as_view(),
        name="candidates-list-by-votes-list-data",
    ),
    re_path(
        r"^ajax/download-candidates-list/$",
        candidate_list_view.get_candidates_list,
        name="download-candidates-list",
    ),
    re_path(
        r"^data/candidate-list-per-office/(?P<tally_id>(\d+))/"
        r"(?P<office_id>(\d+))/$",
        candidate_list_view.CandidateListView.as_view(),
        name="candidate-list-per-office",
    ),
    re_path(
        r"^data/candidate-list-data-per-office/(?P<tally_id>(\d+))/"
        r"(?P<office_id>(\d+))/$",
        candidate_list_view.CandidateListDataView.as_view(),
        name="candidate-list-data-per-office",
    ),
    re_path(
        r"^ajax/download-result-forms/$",
        form_list_view.get_result_forms,
        name="download-result-forms",
    ),
    re_path(
        r"^data/form-list/(?P<tally_id>(\d+))/$",
        form_list_view.FormListView.as_view(),
        name="form-list",
    ),
    re_path(
        r"^data/form-list/(?P<tally_id>(\d+))/(?P<state>.*)/$",
        form_list_view.FormListView.as_view(),
        name="form-list",
    ),
    re_path(
        r"^data/form-list-data/(?P<tally_id>(\d+))/$",
        form_list_view.FormListDataView.as_view(),
        name="form-list-data",
    ),
    re_path(
        r"^data/form-not-received.(?P<format>(csv))/(?P<tally_id>(\d+))/$",
        form_list_view.FormNotReceivedListView.as_view(),
        name="form-not-received-view",
    ),
    re_path(
        r"^data/form-not-received/(?P<tally_id>(\d+))/$",
        form_list_view.FormNotReceivedListView.as_view(),
        name="form-not-received-view",
    ),
    re_path(
        r"^data/form-not-received-data/(?P<tally_id>(\d+))/$",
        form_list_view.FormNotReceivedDataView.as_view(),
        name="form-not-received-data",
    ),
    re_path(
        r"^data/forms-for-race/(?P<tally_id>(\d+))/(?P<ballot>.*)/$",
        form_list_view.FormsForRaceView.as_view(),
        name="forms-for-race",
    ),
    re_path(
        r"^data/forms-for-race-data/(?P<tally_id>(\d+))/(?P<ballot>.*)/$",
        form_list_view.FormListDataView.as_view(),
        name="forms-for-race-data",
    ),
    re_path(
        r"^super-administrator/tallies$",
        super_admin.TalliesView.as_view(),
        name="super-administrator-tallies",
    ),
    re_path(
        r"^super-administrator/(?P<tally_id>(\d+))/$",
        super_admin.DashboardView.as_view(),
        name="super-administrator",
    ),
    re_path(
        r"^super-administrator/create-form/(?P<tally_id>(\d+))/$",
        super_admin.CreateResultFormView.as_view(),
        name="create-form",
    ),
    re_path(
        r"^super-administrator/update-form/(?P<tally_id>(\d+))/"
        r"(?P<form_id>(\d+))$",
        super_admin.EditResultFormView.as_view(),
        name="update-form",
    ),
    re_path(
        r"^super-administrator/delete-form/(?P<tally_id>(\d+))/"
        r"(?P<form_id>(\d+))$",
        super_admin.RemoveResultFormConfirmationView.as_view(),
        name="remove-form-confirmation",
    ),
    re_path(
        r"^super-administrator/form-progress/(?P<tally_id>(\d+))/$",
        super_admin.FormProgressView.as_view(),
        name="form-progress",
    ),
    re_path(
        r"^super-administrator/form-progress-by-form-state/(?P<tally_id>(\d+))/$",
        super_admin.FormProgressByFormStateView.as_view(),
        name="form-progress-by-form-state",
    ),
    re_path(
        r"^super-administrator/form-duplicates/(?P<tally_id>(\d+))/$",
        super_admin.FormDuplicatesView.as_view(),
        name="form-duplicates",
    ),
    re_path(
        r"^super-administrator/form-clearance/(?P<tally_id>(\d+))/$",
        super_admin.FormClearanceView.as_view(),
        name="form-clearance",
    ),
    re_path(
        r"^super-administrator/form-audit/(?P<tally_id>(\d+))/$",
        super_admin.FormAuditView.as_view(),
        name="form-audit",
    ),
    re_path(
        r"^super-administrator/form-action-list/(?P<tally_id>(\d+))/$",
        super_admin.FormActionView.as_view(),
        name="form-action-view",
    ),
    re_path(
        r"^super-administrator/duplicate-result-tracking/"
        r"(?P<tally_id>(\d+))/$",
        super_admin.DuplicateResultTrackingView.as_view(),
        name="duplicate-result-tracking",
    ),
    re_path(
        r"^super-administrator/duplicate_result_form/(?P<tally_id>(\d+))/"
        r"(?P<barcode>(\d+))/(?P<ballot_id>(\d+))/$",
        super_admin.DuplicateResultFormView.as_view(),
        name="duplicate_result_form",
    ),
    re_path(
        r"^super-administrator/form-progress-data/(?P<tally_id>(\d+))/$",
        super_admin.FormProgressDataView.as_view(),
        name="form-progress-data",
    ),
    re_path(
        r"^super-administrator/form-progress-by-form-state-data/(?P<tally_id>(\d+))/$",
        super_admin.FormProgressByFormStateDataView.as_view(),
        name="form-progress-by-form-state-data",
    ),
    re_path(
        r"^super-administrator/form-duplicates-data/(?P<tally_id>(\d+))/$",
        super_admin.FormDuplicatesDataView.as_view(),
        name="form-duplicates-data",
    ),
    re_path(
        r"^super-administrator/form-clearance-data/(?P<tally_id>(\d+))/$",
        super_admin.FormClearanceDataView.as_view(),
        name="form-clearance-data",
    ),
    re_path(
        r"^super-administrator/form-audit-data/(?P<tally_id>(\d+))/$",
        super_admin.FormAuditDataView.as_view(),
        name="form-audit-data",
    ),
    re_path(
        r"^super-administrator/form-results-data/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ResultFormResultsListDataView.as_view(),
        name="form-results-data",
    ),
    re_path(
        r"^super-administrator/form-results/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ResultFormResultsListView.as_view(),
        name="form-results",
    ),
    re_path(
        r"^super-administrator/duplicate-result-form-results-data/"
        r"(?P<tally_id>(\d+))/$",
        administrative_areas_reports.DuplicateResultsListDataView.as_view(),
        name="duplicate-results-data",
    ),
    re_path(
        r"^super-administrator/duplicate-result-form-results/"
        r"(?P<tally_id>(\d+))/$",
        administrative_areas_reports.DuplicateResultsListView.as_view(),
        name="result-forms-with-duplicate-results",
    ),
    re_path(
        r"^super-administrator/all-candidate-votes-data/"
        r"(?P<tally_id>(\d+))/$",
        administrative_areas_reports.AllCandidatesVotesDataView.as_view(),
        name="all-candidates-votes-data",
    ),
    re_path(
        r"^super-administrator/all-candidates-votes/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.AllCandidatesVotesListView.as_view(),
        name="all-candidates-votes",
    ),
    re_path(
        r"^super-administrator/active-candidate-votes-data/"
        r"(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ActiveCandidatesVotesDataView.as_view(),
        name="active-candidates-votes-data",
    ),
    re_path(
        r"^super-administrator/active-candidates-votes/"
        r"(?P<tally_id>(\d+))/$",
        administrative_areas_reports.ActiveCandidatesVotesListView.as_view(),
        name="active-candidates-votes",
    ),
    re_path(
        r"^ajax/get-centers-stations/$",
        administrative_areas_reports.get_centers_stations,
        name="get-centers-stations",
    ),
    re_path(
        r"^ajax/get-export/$",
        administrative_areas_reports.get_export,
        name="get-export",
    ),
    re_path(
        r"^ajax/download-results/$",
        administrative_areas_reports.get_results,
        name="download-results",
    ),
    re_path(
        r"^ajax/download-centers-by-mun-results/$",
        administrative_areas_reports.get_centers_by_municipalities_results,
        name="download-centers-by-mun-results",
    ),
    re_path(
        r"^ajax/download-centers-by-mun-results-candidates-votes/$",
        administrative_areas_reports.get_centers_by_municipalities_candidates_results,
        name="download-centers-by-mun-results-candidates-votes",
    ),
    re_path(
        r"^ajax/download-centers-stations-by-mun-results-candidates-votes/$",
        administrative_areas_reports.get_centers_stations_by_municipalities_candidates_results,
        name="download-centers-stations-by-mun-results-candidates-votes",
    ),
    re_path(
        r"^ajax/download-sub-cons-list/$",
        administrative_areas_reports.get_sub_cons_list,
        name="download-sub-cons-list",
    ),
    re_path(
        r"^super-administrator/results-(?P<report>.*).csv/"
        r"(?P<tally_id>(\d+))/$",
        super_admin.ResultExportView.as_view(),
        name="result-export",
    ),
    re_path(
        r"^super-administrator/results/(?P<tally_id>(\d+))/$",
        super_admin.ResultExportView.as_view(),
        name="result-export",
    ),
    re_path(
        r"^super-administrator/candidate-results/(?P<tally_id>(\d+))/$",
        candidate_results.CandidateResultsView.as_view(),
        name="candidate-results",
    ),
    re_path(
        r"^super-administrator/candidate-results-data/(?P<tally_id>(\d+))/$",
        candidate_results.CandidateResultsDataView.as_view(),
        name="candidate-results-data",
    ),
    re_path(
        r"^super-administrator/remove-center/(?P<tally_id>(\d+))/$",
        super_admin.RemoveCenterView.as_view(),
        name="remove-center",
    ),
    re_path(
        r"^super-administrator/remove-center/(?P<tally_id>(\d+))/"
        r"(?P<center_code>(\d+))$",
        super_admin.RemoveCenterConfirmationView.as_view(),
        name="remove-center-confirmation",
    ),
    re_path(
        r"^super-administrator/edit-center/(?P<tally_id>(\d+))/"
        r"(?P<center_code>(\d+))/$",
        super_admin.EditCenterView.as_view(),
        name="edit-center",
    ),
    re_path(
        r"^super-administrator/create-center/(?P<tally_id>(\d+))/$",
        super_admin.CreateCenterView.as_view(),
        name="create-center",
    ),
    re_path(
        r"^super-administrator/disable/(?P<tally_id>(\d+))/"
        r"(?P<center_code>(\d+))/(?P<station_number>(\d+))?$",
        super_admin.DisableEntityView.as_view(),
        name="disable",
    ),
    re_path(
        r"^super-administrator/enable/(?P<tally_id>(\d+))/"
        r"(?P<center_code>(\d+))/(?P<station_number>(\d+))?$",
        super_admin.EnableEntityView.as_view(),
        name="enable",
    ),
    re_path(
        r"^super-administrator/create-ballot/(?P<tally_id>(\d+))/$",
        super_admin.CreateBallotView.as_view(),
        name="create-ballot",
    ),
    re_path(
        r"^super-administrator/edit-ballot/(?P<tally_id>(\d+))/"
        r"(?P<id>(\d+))$",
        super_admin.EditBallotView.as_view(),
        name="edit-ballot",
    ),
    re_path(
        r"^data/sub-cons-list-data/(?P<tally_id>(\d+))/$",
        sub_constituency_list_view.SubConstituencyListDataView.as_view(),
        name="sub-cons-list-data",
    ),
    re_path(
        r"^data/sub-cons-list/(?P<tally_id>(\d+))/$",
        sub_constituency_list_view.SubConstituencyListView.as_view(),
        name="sub-cons-list",
    ),
    re_path(
        r"^data/electrol-race-list-data/(?P<tally_id>(\d+))/$",
        electrol_race_list_view.ElectrolRaceListDataView.as_view(),
        name="electrol-race-list-data",
    ),
    re_path(
        r"^data/electrol-race-list/(?P<tally_id>(\d+))/$",
        electrol_race_list_view.ElectrolRaceListView.as_view(),
        name="electrol-race-list",
    ),
    re_path(
        r"^super-administrator/create-electrol-race/(?P<tally_id>(\d+))/$",
        super_admin.CreateElectrolRaceView.as_view(),
        name="create-electrol-race",
    ),
    re_path(
        r"^super-administrator/edit-electrol-race/(?P<tally_id>(\d+))/"
        r"(?P<id>(\d+))$",
        super_admin.EditElectrolRaceView.as_view(),
        name="edit-electrol-race",
    ),
    re_path(
        r"^super-administrator/disable-electrol-race/(?P<tally_id>(\d+))/"
        r"(?P<electrol_race_id>(\d+))$",
        super_admin.DisableElectrolRaceView.as_view(),
        name="disable-electrol-race",
    ),
    re_path(
        r"^super-administrator/enable-electrol-race/(?P<tally_id>(\d+))/"
        r"(?P<electrol_race_id>(\d+))$",
        super_admin.EnableElectrolRaceView.as_view(),
        name="enable-electrol-race",
    ),
    re_path(
        r"^super-administrator/disable-ballot/(?P<tally_id>(\d+))/"
        r"(?P<ballot_id>(\d+))$",
        super_admin.DisableBallotView.as_view(),
        name="disable-ballot",
    ),
    re_path(
        r"^super-administrator/enable-ballot/(?P<tally_id>(\d+))/"
        r"(?P<ballot_id>(\d+))$",
        super_admin.EnableBallotView.as_view(),
        name="enable-ballot",
    ),
    re_path(
        r"^super-administrator/candidate-disable/(?P<tally_id>(\d+))/"
        r"(?P<candidateId>(\d+))$",
        super_admin.DisableCandidateView.as_view(),
        name="candidate-disable",
    ),
    re_path(
        r"^super-administrator/candidate-enable/(?P<tally_id>(\d+))/"
        r"(?P<candidateId>(\d+))$",
        super_admin.EnableCandidateView.as_view(),
        name="candidate-enable",
    ),
    re_path(
        r"^super-administrator/create-station/(?P<tally_id>(\d+))/$",
        super_admin.CreateStationView.as_view(),
        name="create-station",
    ),
    re_path(
        r"^super-administrator/remove-station/(?P<tally_id>(\d+))/$",
        super_admin.RemoveStationView.as_view(),
        name="remove-station",
    ),
    re_path(
        r"^super-administrator/quarantine-checks/(?P<tally_id>(\d+))$",
        super_admin.QuarantineChecksListView.as_view(),
        name="quarantine-checks",
    ),
    re_path(
        r"^super-administrator/quarantine-checks/config/"
        r"(?P<tally_id>(\d+))/(?P<checkId>(\d+))$",
        super_admin.QuarantineChecksConfigView.as_view(),
        name="quarantine-checks-config",
    ),
    re_path(
        r"^super-administrator/remove-station/(?P<tally_id>(\d+))/"
        r"(?P<station_id>(\d+))$",
        super_admin.RemoveStationConfirmationView.as_view(),
        name="remove-station-confirmation",
    ),
    re_path(
        r"^super-administrator/edit-station/(?P<tally_id>(\d+))/"
        r"(?P<station_id>(\d+))$",
        super_admin.EditStationView.as_view(),
        name="edit-station",
    ),
    re_path(
        r"^super-admin/user-list/(?P<tally_id>(\d+))/$",
        user_list_view.UserTallyListView.as_view(),
        name="user-tally-list",
    ),
    re_path(
        r"^super-admin/user-list-data/(?P<role>(user|admin))/"
        r"(?P<tally_id>(\d+))/$",
        user_list_view.UserTallyListDataView.as_view(),
        name="user-tally-list-data",
    ),
    re_path(
        r"^super-admin/edit-user/(?P<role>(user|admin))/"
        r"(?P<tally_id>(\d+))/(?P<user_id>(\d+))/$",
        super_admin.EditUserView.as_view(),
        name="edit-user-tally",
    ),
    re_path(
        r"^super-admin/create-user/(?P<tally_id>(\d+))/$",
        super_admin.CreateUserView.as_view(),
        name="create-user-tally",
    ),
    re_path(
        r"^data-entry/(?P<tally_id>(\d+))/$",
        data_entry.DataEntryView.as_view(),
        name="data-entry",
    ),
    re_path(
        r"^data-entry/enter-center-details/(?P<tally_id>(\d+))/$",
        data_entry.CenterDetailsView.as_view(),
        name="data-entry-enter-center-details",
    ),
    re_path(
        r"^data-entry/enter-results/(?P<tally_id>(\d+))/$",
        data_entry.EnterResultsView.as_view(),
        name="enter-results",
    ),
    re_path(
        r"^data-entry/success/(?P<tally_id>(\d+))/$",
        data_entry.ConfirmationView.as_view(),
        name="data-entry-success",
    ),
    re_path(
        r"^intake/center-details/(?P<tally_id>(\d+))/$",
        intake.CenterDetailsView.as_view(),
        name="intake",
    ),
    re_path(
        r"^intake/enter-center/(?P<tally_id>(\d+))/$",
        intake.EnterCenterView.as_view(),
        name="intake-enter-center",
    ),
    re_path(
        r"^intake/check-center-details/(?P<tally_id>(\d+))/$",
        intake.CheckCenterDetailsView.as_view(),
        name="check-center-details",
    ),
    re_path(
        r"^intake/printcover/(?P<tally_id>(\d+))/$",
        intake.PrintCoverView.as_view(),
        name="intake-printcover",
    ),
    re_path(
        r"^intake/clearance/(?P<tally_id>(\d+))/$",
        intake.ClearanceView.as_view(),
        name="intake-clearance",
    ),
    re_path(
        r"^intake/intaken/(?P<tally_id>(\d+))/$",
        intake.ConfirmationView.as_view(),
        name="intaken",
    ),
    re_path(
        r"^intake/intake-printed/(?P<resultFormPk>(\d+))$",
        intake.IntakePrintedView.as_view(),
        name="intake-printed",
    ),
    re_path(
        r"^quality-control/home/(?P<tally_id>(\d+))/$",
        quality_control.QualityControlView.as_view(),
        name="quality-control",
    ),
    re_path(
        r"^quality-control/dashboard/(?P<tally_id>(\d+))/$",
        quality_control.QualityControlDashboardView.as_view(),
        name="quality-control-dashboard",
    ),
    re_path(
        r"^quality-control/confirm-reject/(?P<tally_id>(\d+))/$",
        quality_control.ConfirmFormResetView.as_view(),
        name="quality-control-confirm-reject",
    ),
    re_path(
        r"^quality-control/reject/(?P<tally_id>(\d+))/$",
        TemplateView.as_view(template_name="quality_control/reject.html"),
        name="quality-control-reject",
    ),
    re_path(
        r"^quality-control/print/(?P<tally_id>(\d+))/$",
        quality_control.PrintView.as_view(),
        name="quality-control-print",
    ),
    re_path(
        r"^quality-control/success/(?P<tally_id>(\d+))/$",
        quality_control.ConfirmationView.as_view(),
        name="quality-control-success",
    ),
    re_path(
        r"^corrections/(?P<tally_id>(\d+))/$",
        corrections.CorrectionView.as_view(),
        name="corrections",
    ),
    re_path(
        r"^corrections/match/(?P<tally_id>(\d+))/$",
        corrections.CorrectionMatchView.as_view(),
        name="corrections-match",
    ),
    re_path(
        r"^corrections/required/(?P<tally_id>(\d+))/$",
        corrections.CorrectionRequiredView.as_view(),
        name="corrections-required",
    ),
    re_path(
        r"^corrections/success/(?P<tally_id>(\d+))/$",
        corrections.ConfirmationView.as_view(),
        name="corrections-success",
    ),
    re_path(
        r"^audit/(?P<tally_id>(\d+))/$",
        audit.DashboardView.as_view(),
        name="audit_dashboard",
    ),
    re_path(
        r"^audit/(?P<tally_id>(\d+))/(?P<format>\w+)/$",
        audit.DashboardView.as_view(),
        name="audit_dashboard_csv",
    ),
    re_path(
        r"^audit/new/(?P<tally_id>(\d+))/$",
        audit.CreateAuditView.as_view(),
        name="audit_create",
    ),
    re_path(
        r"^audit/print/(?P<tally_id>(\d+))/$",
        audit.PrintCoverView.as_view(),
        name="audit-print",
    ),
    re_path(
        r"^audit/review/(?P<tally_id>(\d+))/$",
        audit.ReviewView.as_view(),
        name="audit-review",
    ),
    re_path(
        r"^audit/recall-requests/csv/(?P<tally_id>(\d+))/$",
        audit.AuditRecallRequestsCsvView.as_view(),
        name="audit_recall_requests_csv",
    ),
    re_path(
        r"^clearance/(?P<tally_id>(\d+))/$",
        clearance.DashboardView.as_view(),
        name="clearance",
    ),
    re_path(
        r"^clearance/(?P<tally_id>(\d+))/(?P<format>(csv))/$",
        clearance.DashboardView.as_view(),
        name="clearance-csv",
    ),
    re_path(
        r"^clearance/new/(?P<tally_id>(\d+))/$",
        super_admin.CreateResultFormView.as_view(clearance_result_form=True),
        name="clearance-new",
    ),
    re_path(
        r"^clearance/print/(?P<tally_id>(\d+))/$",
        clearance.PrintCoverView.as_view(),
        name="clearance-print",
    ),
    re_path(
        r"^clearance/review/(?P<tally_id>(\d+))/$",
        clearance.ReviewView.as_view(),
        name="clearance-review",
    ),
    re_path(
        r"^clearance/create/(?P<tally_id>(\d+))/$",
        clearance.CreateClearanceView.as_view(),
        name="clearance-create",
    ),
    re_path(
        r"^clearance/check-center-details/(?P<tally_id>(\d+))/$",
        clearance.CheckCenterDetailsView.as_view(),
        name="clearance-check-center-details",
    ),
    re_path(
        r"^clearance/add/(?P<tally_id>(\d+))/$",
        clearance.AddClearanceFormView.as_view(),
        name="clearance-add",
    ),
    re_path(
        r"^clearance/clearance-printed/(?P<resultFormPk>(\d+))$",
        clearance.ClearancePrintedView.as_view(),
        name="clearance-printed",
    ),
    re_path(
        r"^reports/internal/regions/(?P<tally_id>(\d+))/$",
        administrative_areas_reports.RegionsReportsView.as_view(),
        name="reports-regions",
    ),
    re_path(
        r"^reports/internal/regions/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/"
        r"(?P<report_type>(centers-and-stations-in-audit-report))/$",
        administrative_areas_reports.RegionsReportsView.as_view(),
        name="regions-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/regions/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/"
        r"(?P<report_type>"
        r"(centers-and-stations-under-investigation))/$",
        administrative_areas_reports.RegionsReportsView.as_view(),
        name="regions-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/regions/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/"
        r"(?P<report_type>"
        r"(centers-and-stations-excluded-after-investigation))/$",
        administrative_areas_reports.RegionsReportsView.as_view(),
        name="regions-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/regions/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/"
        r"(?P<report_type>(votes-per-candidate-report))/$",
        administrative_areas_reports.RegionsReportsView.as_view(),
        name="region-votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/constituencies/discrepancy/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(
            template_name="reports/process_discrepancy_report.html"
        ),
        name="constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/constituencies/under-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(
            template_name="reports/admin_areas_under_investigation.html"
        ),
        name="constituencies-under-investigation-report",
    ),
    re_path(
        r"^reports/internal/constituencies/after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(
            template_name=str(
                "reports/admin_areas_excluded_after_investigation.html"
            )
        ),
        name="constituencies-excluded-after-investigation-report",
    ),
    re_path(
        r"^reports/internal/constituencies/centers-and-stations-in-audit/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/"
        r"(?P<report_type>(centers-and-stations-in-audit-report))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(),
        name="constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/constituencies/"
        r"centers-and-stations-excluded-after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/"
        r"(?P<report_type>"
        r"(centers-and-stations-under-investigation))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(),
        name="constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/constituencies/"
        r"centers-and-stations-excluded-after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/"
        r"(?P<report_type>"
        r"(centers-and-stations-excluded-after-investigation))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(),
        name="constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/constituencies/progressive/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(
            template_name="reports/progressive_report.html"
        ),
        name="constituency-progressive-report",
    ),
    re_path(
        r"^reports/internal/constituencies/votes-per-candidate/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/"
        r"(?P<report_type>(votes-per-candidate-report))/$",
        administrative_areas_reports.ConstituencyReportsView.as_view(),
        name="constituency-votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/discrepancy/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(
            template_name="reports/process_discrepancy_report.html"
        ),
        name="sub-constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/under-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(
            template_name="reports/admin_areas_under_investigation.html"
        ),
        name="sub-constituencies-under-investigation-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/after-investigation/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(
            template_name=str(
                "reports/admin_areas_excluded_after_investigation.html"
            )
        ),
        name="sub-constituencies-excluded-after-investigation-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/"
        r"centers-and-stations-in-audit/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/"
        r"(?P<report_type>(centers-and-stations-in-audit-report))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(),
        name="sub-constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/"
        r"centers-and-stations-under-investigation/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/"
        r"(?P<report_type>(centers-and-stations-under-investigation))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(),
        name="sub-constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/"
        r"centers-and-stations-excluded-after-investigation/"
        r"(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/"
        r"(?P<report_type>"
        r"(centers-and-stations-excluded-after-investigation))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(),
        name="sub-constituency-discrepancy-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/progressive/"
        r"(?P<tally_id>(\d+))/(?P<region_id>(\d+))/"
        r"(?P<constituency_id>(\d+))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(
            template_name="reports/progressive_report.html"
        ),
        name="sub-constituency-progressive-report",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/"
        r"votes-per-candidate/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/"
        r"(?P<report_type>(votes-per-candidate-report))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(),
        name="sub-constituency-votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/sub-constituencies/"
        r"votes-per-candidate/(?P<tally_id>(\d+))/"
        r"(?P<region_id>(\d+))/(?P<constituency_id>(\d+))/"
        r"(?P<sub_constituency_id>(\d+))/"
        r"(?P<report_type>(candidate-list-sorted-by-ballots-number))/$",
        administrative_areas_reports.SubConstituencyReportsView.as_view(),
        name="sub-constituency-votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/offices/(?P<tally_id>(\d+))/$",
        offices.OfficesReportView.as_view(),
        name="reports-offices",
    ),
    re_path(
        r"^reports/internal/offices/(?P<tally_id>(\d+))/(?P<option>.*)/$",
        offices.OfficesReportDownloadView.as_view(),
        name="reports-offices-export",
    ),
    re_path(
        r"^reports/internal/race/(?P<tally_id>(\d+))/$",
        races.RacesReportView.as_view(),
        name="reports-races",
    ),
    re_path(
        r"^reports/internal/station-progress-list/(?P<tally_id>(\d+))/$",
        station_progress_report.StationProgressListView.as_view(),
        name="station-progress-list",
    ),
    re_path(
        r"^reports/internal/station-progress-list-data/(?P<tally_id>(\d+))"
        r"/$",
        station_progress_report.StationProgressListDataView.as_view(),
        name="station-progress-list-data",
    ),
    re_path(
        r"^reports/internal/station-votes-per-candidate/"
        r"(?P<tally_id>(\d+))/(?P<station_number>(\d+))/$",
        votes_per_candidate.VotesPerCandidateListView.as_view(),
        name="votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/station-votes-per-candidate-list-data/"
        r"(?P<tally_id>(\d+))/(?P<station_number>(\d+))/$",
        votes_per_candidate.VotesPerCandidateListDataView.as_view(),
        name="votes-per-candidate-list-data",
    ),
    re_path(
        r"^reports/internal/center-votes-per-candidate/"
        r"(?P<tally_id>(\d+))/(?P<center_code>(\d+))/$",
        votes_per_candidate.VotesPerCandidateListView.as_view(),
        name="votes-per-candidate",
    ),
    re_path(
        r"^reports/internal/center-votes-per-candidate-list-data/"
        r"(?P<tally_id>(\d+))/(?P<center_code>(\d+))/$",
        votes_per_candidate.VotesPerCandidateListDataView.as_view(),
        name="votes-per-candidate-list-data",
    ),
    re_path(
        r"^reports/internal/staff-performance-metrics/(?P<tally_id>(\d+))/"
        r"(?P<group_name>.*)/$",
        staff_performance_metrics.StaffPerformanceMetricsView.as_view(),
        name="staff-perfomance-metrics",
    ),
    re_path(
        r"^reports/internal/supervisors-approvals/(?P<tally_id>(\d+))/$",
        staff_performance_metrics.SupervisorsApprovalsView.as_view(),
        name="supervisors-approvals",
    ),
    re_path(
        r"^reports/internal/track-corrections/(?P<tally_id>(\d+))/$",
        staff_performance_metrics.TrackCorrections.as_view(),
        name="track-corrections",
    ),
    re_path(
        r"^reports/internal/station-overall-votes/(?P<tally_id>(\d+))/$",
        overall_votes.OverallVotes.as_view(),
        name="station-overall-votes",
    ),
    re_path(
        r"^reports/internal/election-statistics-report/"
        r"(?P<tally_id>(\d+))/(?P<election_level>[\w\-]+)/$",
        election_statistics_report.ElectionStatisticsReportView.as_view(),
        name="election-statistics-report",
    ),
    re_path(
        r"^reports/internal/election-statistics-data/"
        r"(?P<tally_id>(\d+))/(?P<election_level>[\w\-]+)/$",
        election_statistics_report.ElectionStatisticsDataView.as_view(),
        name="election-statistics-data",
    ),
    re_path(
        r"^reports/internal/center-overall-votes/(?P<tally_id>(\d+))/$",
        overall_votes.OverallVotes.as_view(),
        name="center-overall-votes",
    ),
    re_path(
        r"^tally-manager$",
        tally_manager.DashboardView.as_view(),
        name="tally-manager",
    ),
    re_path(
        r"^tally-manager/global-settings/(?P<site_id>(\d+))/$",
        tally_manager.SetUserTimeOutView.as_view(),
        name="global-settings",
    ),
    re_path(
        r"^tally-manager/user-list/(?P<role>(user|admin))$",
        user_list_view.UserListView.as_view(),
        name="user-list",
    ),
    re_path(
        r"^tally-manager/user-list-data/(?P<role>(user|admin))$",
        user_list_view.UserListDataView.as_view(),
        name="user-list-data",
    ),
    re_path(
        r"^tally-manager/remove-user/(?P<role>(user|admin))/"
        r"(?P<user_id>(\d+))/$",
        tally_manager.RemoveUserConfirmationView.as_view(),
        name="remove-user-confirmation",
    ),
    re_path(
        r"^tally-manager/edit-user/(?P<role>(user|admin))/"
        r"(?P<user_id>(\d+))/$",
        tally_manager.EditUserView.as_view(),
        name="edit-user",
    ),
    re_path(
        r"^tally-manager/edit-user/(?P<role>(user|admin))/"
        r"(?P<tally_id>(\d+))/(?P<user_id>(\d+))/$",
        tally_manager.EditUserView.as_view(),
        name="edit-user",
    ),
    re_path(
        r"^tally-manager/create-user/(?P<role>(user|admin))$",
        tally_manager.CreateUserView.as_view(),
        name="create-user",
    ),
    re_path(
        r"^tally-manager/remove-user/(?P<role>(user|admin))/"
        r"(?P<tally_id>(\d+))/(?P<user_id>(\d+))/$",
        tally_manager.RemoveUserConfirmationView.as_view(),
        name="remove-user-confirmation",
    ),
    re_path(
        r"^tally-manager/create-tally$",
        tally_manager.CreateTallyView.as_view(),
        name="create-tally",
    ),
    re_path(
        r"^tally-manager/update-tally/(?P<tally_id>(\d+))/$",
        tally_manager.TallyUpdateView.as_view(),
        name="update-tally",
    ),
    re_path(
        r"^tally-manager/tally-files/(?P<tally_id>(\d+))/$",
        tally_manager.TallyFilesFormView.as_view(),
        name="tally-files-form",
    ),
    re_path(
        r"^tally-manager/remove-tally/(?P<tally_id>(\d+))/$",
        tally_manager.TallyRemoveView.as_view(),
        name="remove-tally",
    ),
    re_path(
        r"^tally-manager/create-tally/batch-view/(?P<tally_id>.*)/"
        r"(?P<ballots_file>.*)/(?P<ballots_file_lines>(\d+))/"
        r"(?P<subconst_file>.*)/(?P<subconst_file_lines>(\d+))/"
        r"(?P<subconst_ballots_file>.*)/"
        r"(?P<subconst_ballots_file_lines>(\d+))/"
        r"(?P<centers_file>.*)/(?P<centers_file_lines>(\d+))/"
        r"(?P<stations_file>.*)/(?P<stations_file_lines>(\d+))/"
        r"(?P<candidates_file>.*)/(?P<candidates_file_lines>(\d+))/"
        r"(?P<ballots_order_file>.*)/(?P<ballots_order_file_lines>(\d+))/"
        r"(?P<result_forms_file>.*)/(?P<result_forms_file_lines>(\d+))/$",
        tally_manager.BatchView.as_view(),
        name="batch-view",
    ),
    re_path(
        r"^tally-manager/data/tally-list$",
        tally_list_view.TallyListView.as_view(),
        name="tally-list",
    ),
    re_path(
        r"^ajax/get-import-progress/(?P<tally_id>(\d+))/$",
        tally_manager.get_import_progress,
        name="get-import-progress",
    ),
    re_path(
        r"^tally-manager/result-form-search$",
        tally_manager.ResultFormSearchView.as_view(),
        name="result-form-search-global",
    ),
    re_path(
        r"^tally-manager/result-form-search/(?P<tally_id>(\d+))/$",
        tally_manager.ResultFormSearchView.as_view(),
        name="result-form-search",
    ),
    re_path(
        r"^tally-manager/result-form-history$",
        tally_manager.ResultFormHistoryView.as_view(),
        name="result-form-history-global",
    ),
    re_path(
        r"^tally-manager/result-form-history/(?P<tally_id>(\d+))/$",
        tally_manager.ResultFormHistoryView.as_view(),
        name="result-form-history",
    ),
    re_path(
        r"^tally-manager/data/tally-list-data$",
        tally_list_view.TallyListDataView.as_view(),
        name="tally-list-data",
    ),
    re_path(
        r"^data/office-list/(?P<tally_id>(\d+))/$",
        office_list_view.OfficeListView.as_view(),
        name="office-list",
    ),
    re_path(
        r"^data/office-list-data/(?P<tally_id>(\d+))/$",
        office_list_view.OfficeListDataView.as_view(),
        name="office-list-data",
    ),
    re_path(
        r"^ajax/download-offices-list/$",
        office_list_view.get_offices_list,
        name="download-offices-list",
    ),
    re_path(
        r"^data/region-list/(?P<tally_id>(\d+))/$",
        region_list_view.RegionListView.as_view(),
        name="region-list",
    ),
    re_path(
        r"^data/region-list-data/(?P<tally_id>(\d+))/$",
        region_list_view.RegionListDataView.as_view(),
        name="region-list-data",
    ),
    re_path(
        r"^ajax/download-regions-list/$",
        region_list_view.get_regions_list,
        name="download-regions-list",
    ),
    re_path(
        r"^data/progress-report-list/(?P<tally_id>(\d+))/$",
        progress_by_sub_races_reports.progress_report,
        name="progress-report-list",
    ),
    re_path(
        r"^data/regions_progress-report/(?P<tally_id>(\d+))/$",
        progress_by_sub_races_reports.RegionsReportView.as_view(),
        name="regions_progress-report",
    ),
    re_path(
        r"^data/offices-progress-report/(?P<tally_id>(\d+))/$",
        progress_by_sub_races_reports.OfficesReportView.as_view(),
        name="offices-progress-report",
    ),
    re_path(
        r"^data/constituencies-progress-report/(?P<tally_id>(\d+))/$",
        progress_by_sub_races_reports.ConstituenciesReportView.as_view(),
        name="constituencies-progress-report",
    ),
    re_path(
        r"^data/sub-constituencies-progress-report/(?P<tally_id>(\d+))/$",
        progress_by_sub_races_reports.SubConstituenciesReportView.as_view(),
        name="sub-constituencies-progress-report",
    ),
    re_path(
        r"^tally/(?P<tally_id>\d+)/workflow/initiate-recall/$",
        InitiateRecallView.as_view(),
        name="initiate_recall_request",
    ),
    re_path(
        r"^tally/(?P<tally_id>\d+)/workflow/create-recall/$",
        CreateRecallRequestView.as_view(),
        name="create_recall_request",
    ),
    re_path(
        r"^tally/(?P<tally_id>\d+)/workflow/recall/(?P<request_pk>\d+)/$",
        RecallRequestDetailView.as_view(),
        name="recall_request_detail",
    ),
    # New URL for viewing result form details during recall
    re_path(
        r"^tally/(?P<tally_id>\d+)/workflow/recall/view_details/(?P<result_form_pk>\d+)/$",
        ViewResultFormDetailsView.as_view(),
        name="view_result_form_details_recall",
    ),
    path(
        "operation-not-allowed", home.suspicious_error, name="suspicious-error"
    ),
    path("accounts/", include(accounts_urls)),
    path("admin/", admin.site.urls),
    path("tracking/", include("tracking.urls")),
    re_path(
        r"^reports/overvoted-forms/(?P<tally_id>(\d+))/$",
        OvervotedResultFormsView.as_view(),
        name="overvoted-forms",
    ),
    re_path(
        r"^data/overvoted-forms-data/(?P<tally_id>(\d+))/$",
        OvervotedResultFormsDataView.as_view(),
        name="overvoted-forms-data",
    ),
    re_path(
        r"^reports/clearance-audit-summary/(?P<tally_id>(\d+))/$",
        ClearanceAuditSummaryReportView.as_view(),
        name="clearance-audit-summary",
    ),
    re_path(
        r"^reports/clearance-audit-summary-data/(?P<tally_id>(\d+))/$",
        ClearanceAuditSummaryReportDataView.as_view(),
        name="clearance-audit-summary-data",
    ),
]

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

    def empty_view(request):
        return JsonResponse({}, status=200)

    urlpatterns += [
        re_path(r"^\.well-known/.*$", empty_view),
    ]
