#!/bin/bash
# copy, compress and upload project

TARGET_HOST=hnec

if [ $# -gt 0 ]; then
    TARGET_HOST=$1
fi

find . -name '*.pyc' -exec rm {} \;
find . -name '._*' -exec rm {} \;
find . -name '.coverage' -exec rm {} \;
find . -name '.DS_Store' -exec rm {} \;
cp -R . ../tally-system-clean
cd ..
rm -rf tally-system-clean/.git
rm -rf tally-system-clean/data/.git
tar czvf tally-system.tgz tally-system-clean
rm -rf tally-system-clean
scp tally-system.tgz $TARGET_HOST:

# login and run install
cat <<RUN
ssh $TARGET_HOST
tar xzvf tally-system.tgz
mv tally-system-clean tally-system
./tally-system/scripts/install_app
RUN
