#!/bin/bash
# copy, compress and upload project

TARGET_HOST=hnec

if [ $# -gt 0 ]; then
    TARGET_HOST=$1
fi

find . -name '*.pyc' -exec rm {} \;
find . -name '._*' -exec rm {} \;
find . -name '.coverage' -exec rm {} \;
find . -name '.DS_Store' -exec rm {} \;
cp -R . ../tally-system-clean
cd ..
rm -rf tally-system-clean/.git
rm -rf tally-system-clean/data/.git
rm -rf tally-system-clean/results
tar czvf tally-system.tgz tally-system-clean
rm -rf tally-system-clean
scp tally-system.tgz $TARGET_HOST:
