#!/bin/bash

PROJECT_HOME=/var/www
PROJECT_NAME="tally-system"
DJANGO_SETTINGS_MODULE="tally_system.settings.local_settings"
CODE_SRC="$PROJECT_HOME/$PROJECT_NAME"
LOG_DIR="/var/log/$PROJECT_NAME"
VENV="$PROJECT_HOME/.virtualenvs"
DB_NAME=tally
DB_USER=tally
DB_PASS=tally
DB_HOST=127.0.0.1
USER=ubuntu
ALLOW_HOST=any

if [ $# -gt 0 ]; then
    DB_HOST=$1
fi

sudo stop tally

if [[ $GIT == "true" ]]; then
    cd $PROJECT_HOME && (git clone git@github.com:onaio/tally-system.git || (cd tally-system && git fetch))
else
    cd $CODE_SRC && sudo cp -rT ~/$PROJECT_NAME/ ./
fi

config_path_tmp="$CODE_SRC/deploy/var/www/tally-system/tally_system/settings/local_settings.py"
config_path="$CODE_SRC/tally_system/settings/local_settings.py"
sudo cp $config_path_tmp $config_path
sudo sed -i.bak -e "s/REPLACE_DB_NAME/$DB_NAME/g" $config_path
sudo sed -i.bak -e "s/REPLACE_DB_USER/$DB_USER/g" $config_path
sudo sed -i.bak -e "s/REPLACE_DB_PASSWORD/$DB_PASS/g" $config_path
sudo sed -i.bak -e "s/REPLACE_DB_HOST/$DB_HOST/g" $config_path

sudo cp "$CODE_SRC/deploy/etc/init/tally.conf" /etc/init/tally.conf
sudo cp "$CODE_SRC/deploy/etc/nginx/sites-available/nginx.conf" /etc/nginx/sites-available/tally.conf
sudo find $CODE_SRC -name '*.pyc' -exec sudo rm {} \;
sudo chown -R $USER:$USER $PROJECT_HOME

sudo /etc/init.d/nginx restart
sudo mkdir -p /var/log/uwsgi
sudo chown -R $USER /var/log/uwsgi
sudo start tally
