# Generated by Django 2.1.1 on 2018-09-13 00:05

from django.db import migrations
import enumfields.fields
import tally_ho.libs.models.enums.center_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_type',
            field=enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.center_type.CenterType, null=True),
        ),
    ]
