# Generated by Django 2.1.1 on 2018-10-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0003_auto_20180927_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='tally',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='tally.Tally'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_user', to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_user', to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='reconciliationform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='resultform',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='resultform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
    ]
