# Generated by Django 2.1.1 on 2018-11-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_auto_20181003_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
        migrations.AlterField(
            model_name='quarantinecheck',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.UserProfile'),
        ),
    ]
