# Generated by Django 2.1.1 on 2018-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_auto_20181115_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('number', 'tally')},
        ),
    ]
