# Generated by Django 2.1.1 on 2018-11-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0006_auto_20181121_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('ballot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.Ballot')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.Center')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tally.Station')),
            ],
        ),
    ]
