# Generated by Django 2.1.1 on 2018-11-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0008_auto_20181128_1900'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resultform',
            index=models.Index(fields=['station_number', 'center', 'ballot', 'tally'], name='tally_resul_station_968b84_idx'),
        ),
    ]
