# Generated by Django 2.1.1 on 2018-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0009_auto_20181130_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tally',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tally.Tally'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ballot', 'tally'], name='tally_comme_ballot__ac21ae_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['center', 'tally'], name='tally_comme_center__87e593_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['station', 'tally'], name='tally_comme_station_30f875_idx'),
        ),
    ]
