# Generated by Django 2.1.1 on 2018-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_auto_20181202_2119'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resultform',
            name='tally_resul_station_968b84_idx',
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['number'], name='tally_ballo_number_620fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='resultform',
            index=models.Index(fields=['center', 'station_number', 'ballot', 'tally'], name='tally_resul_center__d3ba93_idx'),
        ),
    ]
