# Generated by Django 2.1.1 on 2019-01-04 15:13

from django.db import migrations, models
import enumfields.fields
import tally_ho.libs.models.enums.center_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_auto_20181203_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_type',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=tally_ho.libs.models.enums.center_type.CenterType, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='mahalla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='registrants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
