# Generated by Django 2.1.1 on 2019-01-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_auto_20190104_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('station_number', 'center', 'tally')},
        ),
    ]
