# Generated by Django 2.1.1 on 2019-01-16 09:36

from django.db import migrations
import enumfields.fields
import tally_ho.libs.models.enums.form_state


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0013_auto_20190104_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultform',
            name='previous_form_state',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=tally_ho.libs.models.enums.form_state.FormState, null=True),
        ),
    ]
