# Generated by Django 2.1.1 on 2019-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0013_auto_20190104_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
