# Generated by Django 2.1.1 on 2019-01-28 09:01

from django.db import migrations, models
import tally_ho.apps.tally.models.ballot


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_resultform_previous_form_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=tally_ho.apps.tally.models.ballot.ballot_document_directory_path),
        ),
    ]
