# Generated by Django 2.1.1 on 2019-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_resultform_previous_form_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultform',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
