# Generated by Django 2.1.1 on 2019-01-22 13:14

from django.db import migrations, models
import tally_ho.apps.tally.models.ballot


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_ballot_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=tally_ho.apps.tally.models.ballot.ballot_directory_path),
        ),
    ]
