# Generated by Django 2.1.1 on 2019-01-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_auto_20190122_1314'),
        ('tally', '0014_resultform_previous_form_state'),
    ]

    operations = [
    ]
