# Generated by Django 2.1.1 on 2019-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_auto_20190129_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultform',
            name='duplicate_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
