# Generated by Django 2.1.1 on 2019-02-14 08:49

from django.db import migrations
import uuid


def gen_unique_uuid(apps, schema_editor):
    Ballot = apps.get_model('tally', 'Ballot')
    for row in Ballot.objects.all():
        row.unique_uuid = uuid.uuid4()
        row.save(update_fields=['unique_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_auto_20190214_0848'),
    ]

    operations = [
        migrations.RunPython(
            gen_unique_uuid, reverse_code=migrations.RunPython.noop),
    ]
