# Generated by Django 2.1.1 on 2019-01-28 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_ballot_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='unique_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
