# Generated by Django 2.1.1 on 2019-02-14 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0016_auto_20190214_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='unique_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
