# Generated by Django 2.1.1 on 2020-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0018_resultformstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultformstats',
            name='for_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultformstats',
            name='reviewed_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
