# Generated by Django 2.1.1 on 2020-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0019_auto_20200227_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultformstats',
            name='sent_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
