# Generated by Django 2.1.1 on 2020-03-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0020_resultformstats_sent_for_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultformstats',
            old_name='for_superadmin',
            new_name='approved_by_supervisor',
        ),
    ]
