# Generated by Django 2.1.1 on 2020-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0021_auto_20200302_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultformstats',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='resultformstats',
            name='form_state',
        ),
        migrations.RemoveField(
            model_name='resultformstats',
            name='start_time',
        ),
        migrations.AddField(
            model_name='resultformstats',
            name='processing_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
