# Generated by Django 2.1.1 on 2020-03-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('tally', '0023_remove_resultformstats_sent_for_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('idle_timeout', models.PositiveIntegerField(blank=True, default=60, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
