# Generated by Django 2.1.1 on 2020-03-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('tally', '0023_remove_resultformstats_sent_for_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('idle_timeout', models.PositiveIntegerField(
                    blank=True, default=60, null=True)),
                ('group', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
