# Generated by Django 2.1.1 on 2020-03-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0024_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='tally',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usergroup', to='tally.Tally'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
