# Generated by Django 2.1.1 on 2020-03-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0024_siteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='idle_timeout',
            new_name='user_idle_timeout',
        ),
    ]
