# Generated by Django 2.1.1 on 2020-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0025_auto_20200318_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='user_idle_timeout',
            field=models.PositiveIntegerField(),
        ),
    ]
