# Generated by Django 2.1.1 on 2020-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0026_auto_20200319_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='user_idle_timeout',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
