# Generated by Django 2.1.1 on 2020-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0027_auto_20200320_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultformstats',
            name='has_de_error',
            field=models.BooleanField(default=False),
        ),
    ]
