# Generated by Django 2.1.1 on 2020-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0028_resultformstats_has_de_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultformstats',
            name='has_de_error',
        ),
        migrations.AddField(
            model_name='resultformstats',
            name='data_entry_errors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
