# Generated by Django 2.1.1 on 2020-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0029_auto_20200330_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinecheck',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
