# Generated by Django 2.1.1 on 2020-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0030_quarantinecheck_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationform',
            name='number_blank_ballots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of blank ballots'),
        ),
        migrations.AlterField(
            model_name='reconciliationform',
            name='number_invalid_votes',
            field=models.PositiveIntegerField(verbose_name='Number of invalid votes'),
        ),
    ]
