# Generated by Django 2.1.1 on 2020-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0032_auto_20200715_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
