# Generated by Django 2.1.1 on 2020-11-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0033_auto_20201028_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinecheck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
