# Generated by Django 2.1.1 on 2020-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0034_quarantinecheck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinecheck',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quarantinecheck',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
