# Generated by Django 2.1.1 on 2021-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0036_allcandidatesvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='passed_presidential',
            field=models.NullBooleanField(),
        ),
    ]
