# Generated by Django 2.1.1 on 2021-12-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0037_qualitycontrol_passed_presidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconstituency',
            name='ballot_presidential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sc_presidential', to='tally.Ballot'),
        ),
    ]
