# Generated by Django 2.1.1 on 2021-12-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0038_subconstituency_ballot_presidential'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('name', 'tally', 'region')},
        ),
    ]
