# Generated by Django 2.1.1 on 2023-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0039_auto_20211230_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('code', models.PositiveIntegerField()),
                ('ballot_name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='electrolrace',
            unique_together={('type', 'code')},
        ),
    ]
