# Generated by Django 2.1.1 on 2023-05-23 17:37

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import tally_ho.libs.models.enums.race_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0039_auto_20211230_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('election_level', models.CharField(max_length=256, null=True)),
                ('ballot_name', models.CharField(max_length=256, null=True)),
                ('tally', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electrol_races', to='tally.Tally')),
            ],
            options={
                'ordering': ['ballot_name'],
            },
        ),
        migrations.AddField(
            model_name='subconstituency',
            name='ballots',
            field=models.ManyToManyField(blank=True, related_name='ballots', to='tally.Ballot'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='race_type',
            field=enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.race_type.RaceType, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race_type',
            field=enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.race_type.RaceType, null=True),
        ),
        migrations.AlterField(
            model_name='subconstituency',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constituency', to='tally.Constituency'),
        ),
        migrations.AlterField(
            model_name='subconstituency',
            name='tally',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tally', to='tally.Tally'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='electrol_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='tally.ElectrolRace'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('number', 'tally', 'electrol_race')},
        ),
        migrations.AlterUniqueTogether(
            name='electrolrace',
            unique_together={('election_level', 'ballot_name')},
        ),
    ]
