# Generated by Django 2.1.1 on 2023-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0040_auto_20230523_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subconstituency',
            name='field_office',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
