# Generated by Django 2.1.1 on 2023-05-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0040_auto_20230504_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='electrol_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='tally.ElectrolRace'),
        ),
    ]
