# Generated by Django 2.1.1 on 2023-05-04 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0041_ballot_electrol_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrolrace',
            name='component_ballot_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
