# Generated by Django 2.1.1 on 2023-05-08 07:23

from django.db import migrations
import enumfields.fields
import tally_ho.libs.models.enums.race_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0042_electrolrace_component_ballot_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='race_type',
            field=enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.race_type.RaceType, null=True),
        ),
    ]
