# Generated by Django 2.1.1 on 2023-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0043_candidate_electrol_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='passed_qc',
            field=models.NullBooleanField(),
        ),
    ]
