# Generated by Django 2.1.1 on 2023-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0043_auto_20230508_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconstituency',
            name='ballots',
            field=models.ManyToManyField(blank=True, related_name='ballots', to='tally.Ballot'),
        ),
    ]
