# Generated by Django 2.1.1 on 2023-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0044_qualitycontrol_passed_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subconstituency',
            name='ballots',
            field=models.ManyToManyField(blank=True, related_name='sub_cons', to='tally.Ballot'),
        ),
    ]
