# Generated by Django 2.1.1 on 2023-05-10 11:15

from django.db import migrations
import enumfields.fields
import tally_ho.libs.models.enums.race_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0046_auto_20230508_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='race_type',
            field=enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.race_type.RaceType, null=True),
        ),
    ]
