# Generated by Django 2.1.1 on 2023-06-09 09:48

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import tally_ho.libs.models.enums.disable_reason


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0046_auto_20230609_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='electrol_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='tally.ElectrolRace'),
        ),
        migrations.AddField(
            model_name='electrolrace',
            name='disable_reason',
            field=enumfields.fields.EnumIntegerField(default=None, enum=tally_ho.libs.models.enums.disable_reason.DisableReason, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['electrol_race', 'tally'], name='tally_comme_electro_e24fd7_idx'),
        ),
    ]
