# Generated by Django 2.1.1 on 2023-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0047_auto_20230609_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconstituency',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
