# Generated by Django 4.2.2 on 2023-06-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0040_alter_qualitycontrol_passed_general_and_more'),
        ('tally', '0048_subconstituency_name'),
    ]

    operations = [
    ]
