# Generated by Django 2.1.1 on 2023-05-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0048_auto_20230511_0807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('number', 'tally', 'electrol_race')},
        ),
    ]
