# Generated by Django 2.1.1 on 2023-05-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0049_auto_20230511_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrolrace',
            old_name='type',
            new_name='election_level',
        ),
        migrations.AlterUniqueTogether(
            name='electrolrace',
            unique_together={('election_level', 'code')},
        ),
    ]
