# Generated by Django 4.2.2 on 2023-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0049_merge_20230615_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='passed_qc',
            field=models.BooleanField(null=True),
        ),
    ]
