# Generated by Django 4.2.2 on 2023-06-22 13:07

from django.db import migrations, models
import tally_ho.apps.tally.models.electrol_race


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0050_alter_qualitycontrol_passed_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrolrace',
            name='background_image',
            field=models.FileField(blank=True, default='', null=True, upload_to=tally_ho.apps.tally.models.electrol_race.bck_grnd_img_directory_path),
        ),
    ]
