# Generated by Django 4.2.2 on 2024-08-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0051_electrolrace_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationform',
            name='number_blank_ballots',
        ),
    ]
