# Generated by Django 2.1.1 on 2023-05-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0051_auto_20230523_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrolrace',
            name='code',
        ),
    ]
