# Generated by Django 4.2.2 on 2024-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0052_remove_reconciliationform_number_blank_ballots'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationform',
            name='number_of_voter_cards_in_the_ballot_box',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of voter cards in the ballot box'),
        ),
    ]
