# Generated by Django 2.1.1 on 2023-05-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0053_remove_electrolrace_component_ballot_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrolrace',
            name='tally',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electrol_races', to='tally.Tally'),
        ),
    ]
