# Generated by Django 4.2.2 on 2024-10-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0053_reconciliationform_number_of_voter_cards_in_the_ballot_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationform',
            name='number_signatures_in_vr',
        ),
    ]
