# Generated by Django 4.2.2 on 2024-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0054_remove_reconciliationform_number_signatures_in_vr'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationform',
            name='total_of_fields_5_and_7',
            field=models.PositiveIntegerField(default=0, verbose_name='Total of fields 5+7'),
        ),
    ]
