# Generated by Django 4.2.2 on 2024-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0055_reconciliationform_total_of_cancelled_ballots_and_ballots_inside_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationform',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
