# Generated by Django 4.2.2 on 2025-04-15 14:20

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import tally_ho.libs.models.enums.request_reason
import tally_ho.libs.models.enums.request_status
import tally_ho.libs.models.enums.request_type


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0057_alter_reconciliationform_ballot_number_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('request_type', enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.request_type.RequestType, verbose_name='Request Type')),
                ('status', enumfields.fields.EnumIntegerField(default=0, enum=tally_ho.libs.models.enums.request_status.RequestStatus, verbose_name='Request Status')),
                ('request_reason', enumfields.fields.EnumIntegerField(enum=tally_ho.libs.models.enums.request_reason.RequestReason, verbose_name='Reason')),
                ('request_comment', models.TextField(verbose_name='Request Comment')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='Approval/Rejection Comment')),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_rejected_requests', to='tally.userprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_requests', to='tally.userprofile')),
                ('result_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests', to='tally.resultform')),
            ],
            options={
                'indexes': [models.Index(fields=['result_form', 'request_type', 'status'], name='tally_workf_result__92f4e2_idx')],
            },
        ),
    ]
