# Generated by Django 4.2.2 on 2025-04-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0058_workflowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationform',
            name='deactivated_by_request',
            field=models.ForeignKey(blank=True, help_text='The workflow request that triggered the deactivation of this reconciliation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_recons', to='tally.workflowrequest'),
        ),
        migrations.AddField(
            model_name='result',
            name='deactivated_by_request',
            field=models.ForeignKey(blank=True, help_text='The workflow request that triggered the deactivation of this result record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_results', to='tally.workflowrequest'),
        ),
    ]
