# Generated by Django 4.2.2 on 2025-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0059_reconciliationform_deactivated_by_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='print_cover_in_audit',
            field=models.BooleanField(default=True, help_text='Enable/disable cover printing in Audit stage'),
        ),
        migrations.AddField(
            model_name='tally',
            name='print_cover_in_clearance',
            field=models.BooleanField(default=True, help_text='Enable/disable cover printing in Clearance stage'),
        ),
        migrations.AddField(
            model_name='tally',
            name='print_cover_in_intake',
            field=models.BooleanField(default=True, help_text='Enable/disable cover printing in Intake stage'),
        ),
        migrations.AddField(
            model_name='tally',
            name='print_cover_in_quality_control',
            field=models.BooleanField(default=True, help_text='Enable/disable cover printing in Quality Control stage'),
        ),
    ]
