# Generated by Django 4.2.2 on 2025-07-12 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tally", "0060_tally_print_cover_in_audit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reconciliationform",
            name="is_stamped",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_ballots_inside_and_outside_box",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_ballots_inside_box",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_ballots_outside_box",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_cancelled_ballots",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_spoiled_ballots",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_unstamped_ballots",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_unused_ballots",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="signature_dated",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="signature_polling_officer_1",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="signature_polling_officer_2",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="signature_polling_station_chair",
        ),
        migrations.RemoveField(
            model_name="reconciliationform",
            name="total_of_cancelled_ballots_and_ballots_inside_box",
        ),
    ]
