# Generated by Django 4.2.2 on 2025-07-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0061_remove_reconciliationform_is_stamped_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reconciliationform",
            name="number_ballots_received",
        ),
    ]
