# Generated by Django 4.2.2 on 2025-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0062_remove_reconciliationform_number_ballots_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationform",
            name="number_of_voters",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="Number of voters in the station's voter register (in addition to additional voters)",
            ),
            preserve_default=False,
        ),
    ]
