# Generated by Django 4.2.2 on 2025-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0063_reconciliationform_number_of_voters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliationform",
            name="number_sorted_and_counted",
            field=models.PositiveIntegerField(
                verbose_name="Total number of ballot papers in the box"
            ),
        ),
    ]
