# Generated by Django 4.2.2 on 2025-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0064_alter_reconciliationform_number_sorted_and_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinecheck',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quarantinecheck',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
