# Generated by Django 4.2.2 on 2025-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0065_alter_quarantinecheck_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultform',
            name='serial_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
