# Generated by Django 4.2.2 on 2025-08-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0067_add_tally_to_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audits",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="clearance",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clearances",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycontrol",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_controls",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationform",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation_forms",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="resultformstats",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="result_form_stats",
                to="tally.tally",
            ),
        ),
        migrations.AlterField(
            model_name="workflowrequest",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_requests",
                to="tally.tally",
            ),
        ),
    ]
