# Generated by Django 4.2.2 on 2025-08-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0068_remove_tally_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultform',
            name='skip_all_zero_votes_check',
            field=models.BooleanField(default=False),
        ),
    ]
