# Generated by Django 4.2.2 on 2025-10-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0069_add_skip_all_zero_votes_check_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
