# Generated by Django 4.2.2 on 2025-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0070_add_active_field_to_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFormReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('result_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.resultform')),
                ('tally', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_form_resets', to='tally.tally')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.userprofile')),
            ],
        ),
    ]
