# Generated by Django 4.2.2 on 2025-12-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0071_add_tally_form_reset"),
    ]

    operations = [
        # Add tally FK field (nullable to allow existing records)
        migrations.AddField(
            model_name="quarantinecheck",
            name="tally",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quarantine_checks",
                to="tally.tally",
            ),
        ),
        # Remove unique constraint from name field
        # This allows duplicate names across different tallies
        migrations.AlterField(
            model_name="quarantinecheck",
            name="name",
            field=models.CharField(max_length=256),
        ),
        # Remove unique constraint from method field
        # This allows duplicate methods across different tallies
        migrations.AlterField(
            model_name="quarantinecheck",
            name="method",
            field=models.CharField(max_length=256),
        ),
    ]
