# Generated by Django 4.2.2 on 2025-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0071_add_tally_form_reset'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['ballot', 'active'], name='tally_candi_ballot__f1e331_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['ballot', 'order'], name='tally_candi_ballot__0bae2e_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['candidate', 'entry_version', 'active', 'result_form'], name='tally_resul_candida_8f45cb_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['result_form', 'entry_version', 'active'], name='tally_resul_result__6c3999_idx'),
        ),
        migrations.AddIndex(
            model_name='resultform',
            index=models.Index(fields=['barcode', 'tally'], name='tally_resul_barcode_1524b5_idx'),
        ),
        migrations.AddIndex(
            model_name='resultform',
            index=models.Index(fields=['form_state', 'tally'], name='tally_resul_form_st_697edb_idx'),
        ),
        migrations.AddIndex(
            model_name='resultform',
            index=models.Index(fields=['ballot', 'form_state', 'tally'], name='tally_resul_ballot__e38497_idx'),
        ),
    ]
