# Generated by Django 4.2.2 on 2025-12-17 00:02

from django.db import migrations


def remap_audit_quarantine_checks(apps, schema_editor):
    """
    Remap audit quarantine check references from global checks to tally-specific checks.

    When audits were created, they referenced global quarantine checks (tally=null).
    Now we need to update those references to point to the tally-specific checks.
    """
    Audit = apps.get_model("tally", "Audit")
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")

    print("\n" + "="*70)
    print("Remapping audit quarantine check references")
    print("="*70 + "\n")

    # Get all audits that have quarantine checks
    audits_with_checks = Audit.objects.prefetch_related('quarantine_checks').filter(
        quarantine_checks__isnull=False
    ).distinct()

    if not audits_with_checks.exists():
        print("No audits with quarantine checks found. Nothing to remap.\n")
        return

    updated_count = 0
    skipped_count = 0

    for audit in audits_with_checks:
        # Get the tally for this audit (via result_form or direct)
        if hasattr(audit, 'tally_id') and audit.tally_id:
            tally_id = audit.tally_id
        elif hasattr(audit, 'result_form') and audit.result_form and hasattr(audit.result_form, 'tally_id'):
            tally_id = audit.result_form.tally_id
        else:
            print(f"⚠️  Audit {audit.id}: Cannot determine tally. Skipping.")
            skipped_count += 1
            continue

        # Get current quarantine checks for this audit
        current_checks = list(audit.quarantine_checks.all())

        if not current_checks:
            continue

        # Clear existing M2M relationships
        audit.quarantine_checks.clear()

        # For each old check, find the corresponding tally-specific check
        remapped = 0
        for old_check in current_checks:
            # Find the tally-specific check with same method
            try:
                new_check = QuarantineCheck.objects.get(
                    method=old_check.method,
                    tally_id=tally_id
                )
                # Add the new check to the audit
                audit.quarantine_checks.add(new_check)
                remapped += 1
            except QuarantineCheck.DoesNotExist:
                print(f"⚠️  Audit {audit.id}: No tally-specific check found for "
                      f"method '{old_check.method}' in tally {tally_id}")
            except QuarantineCheck.MultipleObjectsReturned:
                print(f"⚠️  Audit {audit.id}: Multiple checks found for "
                      f"method '{old_check.method}' in tally {tally_id}")

        if remapped > 0:
            print(f"✓ Audit {audit.id}: Remapped {remapped} check(s) to tally {tally_id}")
            updated_count += 1

    print("\n" + "="*70)
    print("Remapping complete:")
    print(f"  • Updated audits: {updated_count}")
    print(f"  • Skipped audits: {skipped_count}")
    print("="*70 + "\n")


def reverse_remap_audit_quarantine_checks(apps, schema_editor):
    """
    Reverse migration - remap checks back to global checks.

    This restores audit references to point to global checks (tally=null).
    """
    Audit = apps.get_model("tally", "Audit")
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")

    print("\nReversing audit quarantine check remapping...\n")

    audits_with_checks = Audit.objects.prefetch_related('quarantine_checks').filter(
        quarantine_checks__isnull=False
    ).distinct()

    if not audits_with_checks.exists():
        print("No audits with quarantine checks found.\n")
        return

    updated_count = 0

    for audit in audits_with_checks:
        current_checks = list(audit.quarantine_checks.all())

        if not current_checks:
            continue

        # Clear existing M2M relationships
        audit.quarantine_checks.clear()

        # For each tally-specific check, find the corresponding global check
        remapped = 0
        for tally_check in current_checks:
            try:
                # Find global check with same method
                global_check = QuarantineCheck.objects.get(
                    method=tally_check.method,
                    tally__isnull=True
                )
                # Add the global check to the audit
                audit.quarantine_checks.add(global_check)
                remapped += 1
            except QuarantineCheck.DoesNotExist:
                print(f"⚠️  Audit {audit.id}: No global check found for "
                      f"method '{tally_check.method}'")
            except QuarantineCheck.MultipleObjectsReturned:
                print(f"⚠️  Audit {audit.id}: Multiple global checks found for "
                      f"method '{tally_check.method}'")

        if remapped > 0:
            print(f"✓ Audit {audit.id}: Remapped {remapped} check(s) to global")
            updated_count += 1

    print(f"\nReverse remapping complete: Updated {updated_count} audits\n")


class Migration(migrations.Migration):
    dependencies = [
        ("tally", "0073_populate_quarantine_check_tally"),
    ]

    operations = [
        migrations.RunPython(
            remap_audit_quarantine_checks,
            reverse_remap_audit_quarantine_checks,
        ),
    ]
