# Generated by Django 4.2.2 on 2025-12-17 00:01

from django.db import migrations


def populate_tally_for_quarantine_checks(apps, schema_editor):
    """
    Duplicate existing quarantine checks for each tally in the system.

    This ensures every tally has its own set of quarantine checks with
    the default configuration. Original global checks (tally=null) are
    preserved temporarily and will be removed in the next migration.
    """
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")
    Tally = apps.get_model("tally", "Tally")

    # Get all existing quarantine checks (should have tally=null at this point)
    global_checks = QuarantineCheck.objects.filter(tally__isnull=True)

    if not global_checks.exists():
        print("No global quarantine checks found. Skipping duplication.")
        return

    # Get all tallies in the system
    tallies = Tally.objects.all()

    if not tallies.exists():
        print("WARNING: No tallies found in the system!")
        print("Quarantine checks will remain global until tallies are created.")
        return

    tally_count = tallies.count()
    check_count = global_checks.count()

    print(f"\n{'='*70}")
    print(f"Duplicating {check_count} quarantine checks for {tally_count} tallies")
    print(f"{'='*70}\n")

    created_count = 0

    # For each tally, create a copy of each global check
    for tally in tallies:
        print(f"Processing Tally ID {tally.id}: {tally.name if hasattr(tally, 'name') else 'Unnamed'}")

        for check in global_checks:
            # Create a new check for this tally with the same configuration
            new_check = QuarantineCheck.objects.create(
                tally=tally,
                user=check.user,
                name=check.name,
                method=check.method,  # Keep method same for lookup
                value=check.value,
                percentage=check.percentage,
                active=check.active,
                description=check.description,
            )
            created_count += 1
            print(f"  ✓ Created: {new_check.name}")

    print(f"\n{'='*70}")
    print(f"Successfully created {created_count} tally-specific quarantine checks")
    print(f"Original {check_count} global checks will be removed in next migration")
    print(f"{'='*70}\n")


def reverse_populate_tally_for_quarantine_checks(apps, schema_editor):
    """
    Reverse migration - delete all tally-specific checks.

    This will leave only the original global checks (tally=null).
    """
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")

    # Delete all tally-specific checks
    tally_specific_checks = QuarantineCheck.objects.filter(tally__isnull=False)
    count = tally_specific_checks.count()
    tally_specific_checks.delete()

    print(f"\nDeleted {count} tally-specific quarantine checks")
    print("Restored to global checks only\n")


class Migration(migrations.Migration):    
    dependencies = [
        ("tally", "0073_alter_quarantinecheck_add_tally_id"),
    ]

    operations = [
        # Duplicate checks for each tally
        migrations.RunPython(
            populate_tally_for_quarantine_checks,
            reverse_populate_tally_for_quarantine_checks,
        ),
    ]
