# Generated by Django 4.2.2 on 2025-12-17 00:02

from django.db import migrations


def delete_global_quarantine_checks(apps, schema_editor):
    """
    Delete all global quarantine checks (tally=null).

    At this point, all tallies should have their own copies of the checks.
    """
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")

    global_checks = QuarantineCheck.objects.filter(tally__isnull=True)
    count = global_checks.count()

    if count > 0:
        print(f"\nDeleting {count} global quarantine checks...")
        global_checks.delete()
        print(f"✓ Deleted {count} global checks\n")
    else:
        print("\nNo global quarantine checks to delete.\n")


def restore_global_quarantine_checks(apps, schema_editor):
    """
    Reverse migration - recreate one set of global checks.

    This creates global checks based on the first tally's checks.
    """
    QuarantineCheck = apps.get_model("tally", "QuarantineCheck")
    Tally = apps.get_model("tally", "Tally")

    # Get first tally's checks as template
    first_tally = Tally.objects.first()

    if not first_tally:
        print("WARNING: No tallies found. Cannot restore global checks.")
        return

    tally_checks = QuarantineCheck.objects.filter(tally=first_tally)

    if not tally_checks.exists():
        print("WARNING: First tally has no checks. Cannot restore global checks.")
        return

    print(f"\nRestoring global checks from Tally ID {first_tally.id}...")

    for check in tally_checks:
        # Remove the tally-specific suffix from the name
        original_name = check.name.replace(f" (Tally {first_tally.id})", "")

        QuarantineCheck.objects.create(
            tally=None,  # Global check
            user=check.user,
            name=original_name,
            method=check.method,
            value=check.value,
            percentage=check.percentage,
            active=check.active,
            description=check.description,
        )
        print(f"  ✓ Restored: {original_name}")

    print("Global checks restored\n")


class Migration(migrations.Migration):
    dependencies = [
        ("tally", "0074_remap_audit_quarantine_checks"),
    ]

    operations = [
        migrations.RunPython(
            delete_global_quarantine_checks,
            restore_global_quarantine_checks,
        ),
    ]
