# Generated by Django 4.2.2 on 2025-12-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tally", "0075_delete_global_quarantine_checks"),
    ]

    operations = [
        # Add unique_together constraint (method + tally must be unique)
        migrations.AlterUniqueTogether(
            name="quarantinecheck",
            unique_together={("method", "tally"), ("name", "tally")},
        ),
        # Make tally field required (NOT NULL)
        migrations.AlterField(
            model_name="quarantinecheck",
            name="tally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quarantine_checks",
                to="tally.tally",
            ),
        ),
    ]
