# Generated by Django 5.2.8 on 2026-04-28 23:23

import enumfields.fields
import tally_ho.libs.models.enums.pvp_mode
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0077_alter_quarantinecheck_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='pvp_mode',
            field=enumfields.fields.EnumIntegerField(default=0, enum=tally_ho.libs.models.enums.pvp_mode.PvpMode, help_text='Preliminary Vote Protocol ingest mode for this tally'),
        ),
    ]
