# Generated by Django 5.2.8 on 2026-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0078_cleanup_duplicate_active_records'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('result_form',), name='unique_active_audit_per_result_form'),
        ),
        migrations.AddConstraint(
            model_name='clearance',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('result_form',), name='unique_active_clearance_per_result_form'),
        ),
        migrations.AddConstraint(
            model_name='qualitycontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('result_form',), name='unique_active_qc_per_result_form'),
        ),
    ]
