# Generated by Django 5.2.8 on 2026-04-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0079_pvp_upload_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvpSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('odk_instance_id', models.CharField(max_length=255)),
                ('odk_form_id', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('staff_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('round1_raw', models.JSONField(blank=True, default=dict)),
                ('round2_raw', models.JSONField(blank=True, default=dict)),
                ('recon_raw', models.JSONField(blank=True, default=dict)),
                ('clerk_signature', models.FileField(blank=True, null=True, upload_to='pvp/')),
                ('forms_picture_1st_page', models.FileField(blank=True, null=True, upload_to='pvp/')),
                ('forms_picture_2nd_page', models.FileField(blank=True, null=True, upload_to='pvp/')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tally.pvpuploadbundle')),
                ('tally', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally.tally')),
            ],
            options={
                'unique_together': {('tally', 'odk_instance_id')},
            },
        ),
    ]
