# Generated by Django 5.2.8 on 2026-04-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0080_pvp_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultform',
            name='pvp_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_form', to='tally.pvpsubmission'),
        ),
    ]
