name: Django CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-20.04

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub postgres image
        image: postgres:15-alpine
        env:
          POSTGRES_USER: tally
          POSTGRES_DB: tally
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      # Connect Postgres service with custom container image
      # https://github.community/t/connect-postgres-service-with-custom-container-image/189994
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: tally

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/dev.pip') }}
          path: ./venv

      - name: Generate Report
        run: |
          python3 -m venv venv
            . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements/dev.pip
          ruff . --exit-non-zero-on-fix
          coverage run --source='tally_ho' --omit='*/tests/*','*/__init__.py','manage.py','tally_ho/wsgi.py','*/migrations/*','*/venv/*''*/settings/*','*/templates/*' manage.py test --settings=tally_ho.settings.dev
          coverage xml
          ls -al

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
