name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies
        run: uv pip install -r requirements/dev.pip

      - name: Run enhanced ruff security checks
        run: |
          source .venv/bin/activate
          ruff check . --select=S,B --output-format=github
        continue-on-error: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"

      - name: Run Semgrep
        if: github.event_name != 'schedule'
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}